/**
 * EVAMATS / Bitrix persistence slug mappings (OD-006).
 */

export const CAR_TEMPLATE_NOTE_COLUMNS = [
  'notes_general',
  'notes_front_classic',
  'notes_front_3d',
  'notes_rear_classic',
  'notes_rear_3d',
  'notes_third_row',
  'notes_trunk_general',
  'notes_trunk_estate',
  'notes_trunk_hatchback',
  'notes_trunk_sedan',
  'notes_trunk_liftback',
  'notes_trunk_suv_5_seater',
  'notes_trunk_suv_7_seater',
  'notes_trunk_minivan_5_seater',
  'notes_trunk_minivan_7_seater',
] as const;

export type CarTemplateNoteColumn = (typeof CAR_TEMPLATE_NOTE_COLUMNS)[number];

export const EVAMATS_BODY_TYPE_SLUGS: Readonly<Record<string, string>> = {
  suv: 'suv',
  'suv ': 'suv',
  'suv 5 drzwi': 'suv_5_door',
  'suv 5 drzwi ': 'suv_5_door',
  'suv 6 osobowy': 'suv_6_seater',
  'suv 7 osobowy': 'suv_7_seater',
  'suv coupe': 'suv_coupe',
  sedan: 'sedan',
  'sedan ': 'sedan',
  kombi: 'estate',
  hatchback: 'hatchback',
  'hatchback 3 drzwi': 'hatchback_3_door',
  'hatchback 5 drzwi': 'hatchback_5_door',
  'hatchback 5 drzwi ': 'hatchback_5_door',
  'hatchback 3 drzwi ': 'hatchback_3_door',
  coupe: 'coupe',
  'coupe-cabrio': 'coupe_cabrio',
  cabrio: 'convertible',
  kabriolet: 'convertible',
  roadster: 'roadster',
  liftback: 'liftback',
  'liftback ': 'liftback',
  minivan: 'minivan',
  'shooting brake': 'shooting_brake',
  koparka: 'excavator',
  ciagnik: 'tractor',
  ciągnik: 'tractor',
  ladowarka: 'loader',
  ładowarka: 'loader',
  'suv 5os': 'suv_5_seater',
  'suv 7os': 'suv_7_seater',
  'minivan 5os': 'minivan_5_seater',
  'minivan 7os': 'minivan_7_seater',
  van: 'van',
  'van dostawczak': 'van',
  'van dostawczy': 'van',
};

export const POLISH_TO_ENGLISH_TOKENS: Readonly<[string, string][]> = [
  ['osobowy', 'seater'],
  ['osobowe', 'seater'],
  ['drzwi', 'door'],
  ['rzędy', 'row'],
  ['rzedu', 'row'],
  ['rząd', 'row'],
  ['kabriolet', 'convertible'],
  ['kombi', 'estate'],
  ['sedan', 'sedan'],
  ['minivan', 'minivan'],
  ['hatchback', 'hatchback'],
  ['liftback', 'liftback'],
  ['coupe', 'coupe'],
  ['coupe-cabrio', 'coupe_cabrio'],
  ['roadster', 'roadster'],
  ['generacja', 'generation'],
  ['gen', 'gen'],
  ['polift', 'facelift'],
  ['przedlift', 'prefacelift'],
  ['os.', 'seater'],
  ['os', 'seater'],
];
