export enum RequirementLabel {
  YES_NO_INFO = 'YES_NO_INFO',
  OPTION_SELECTION = 'OPTION_SELECTION',
  MEASUREMENT = 'MEASUREMENT',
  TEXT_CONFIRMATION = 'TEXT_CONFIRMATION',
  PHOTO_REQUIRED = 'PHOTO_REQUIRED',
}
