export enum SideEffectType {
  SEND_INITIAL_EMAIL = 'SEND_INITIAL_EMAIL',
  SEND_FOLLOWUP_EMAIL = 'SEND_FOLLOWUP_EMAIL',
  SEND_COMPLETION_CONFIRMATION_EMAIL = 'SEND_COMPLETION_CONFIRMATION_EMAIL',
  UPLOAD_BITRIX_DEAL_PHOTOS = 'UPLOAD_BITRIX_DEAL_PHOTOS',
  UPDATE_BITRIX_STAGE_TO_COMPLETED = 'UPDATE_BITRIX_STAGE_TO_COMPLETED',
  UPDATE_BITRIX_STAGE_TO_ESCALATED = 'UPDATE_BITRIX_STAGE_TO_ESCALATED',
  CREATE_BITRIX_COMMENT = 'CREATE_BITRIX_COMMENT',
  SEND_TELEGRAM_NOTIFICATION = 'SEND_TELEGRAM_NOTIFICATION',
}
