export enum WorkflowStatus {
  STARTED = 'STARTED',
  CONTEXT_LOADED = 'CONTEXT_LOADED',
  TEMPLATE_MATCHED = 'TEMPLATE_MATCHED',
  REQUIREMENTS_CREATED = 'REQUIREMENTS_CREATED',
  WAITING_FOR_CUSTOMER_REPLY = 'WAITING_FOR_CUSTOMER_REPLY',
  REQUIREMENTS_UPDATED = 'REQUIREMENTS_UPDATED',
  COMPLETION_PENDING_BITRIX_UPDATE = 'COMPLETION_PENDING_BITRIX_UPDATE',
  ESCALATION_PENDING_BITRIX_UPDATE = 'ESCALATION_PENDING_BITRIX_UPDATE',
  COMPLETED = 'COMPLETED',
  ESCALATED = 'ESCALATED',
  FAILED = 'FAILED',
}
